/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddCatalogWidgetModal: typeof import('./src/components/AddCatalogWidgetModal.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AssetsByClassWidget: typeof import('./src/components/widgets/AssetsByClassWidget.vue')['default']
    CompositionChart: typeof import('./src/components/CompositionChart.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    ConnectionModeFields: typeof import('./src/components/ConnectionModeFields.vue')['default']
    EllipsisMenu: typeof import('./src/components/EllipsisMenu.vue')['default']
    EntityFormModal: typeof import('./src/components/EntityFormModal.vue')['default']
    LiabilitiesVsAssetsWidget: typeof import('./src/components/widgets/LiabilitiesVsAssetsWidget.vue')['default']
    ListWidget: typeof import('./src/components/widgets/ListWidget.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    NetWorthRings: typeof import('./src/components/NetWorthRings.vue')['default']
    OnboardingScreen: typeof import('./src/components/OnboardingScreen.vue')['default']
    PageLoadingSkeleton: typeof import('./src/components/PageLoadingSkeleton.vue')['default']
    PayoffStatusWidget: typeof import('./src/components/widgets/PayoffStatusWidget.vue')['default']
    RecentValuationsWidget: typeof import('./src/components/widgets/RecentValuationsWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatCard: typeof import('./src/components/StatCard.vue')['default']
    StatCardRow: typeof import('./src/components/StatCardRow.vue')['default']
    StatTileWidget: typeof import('./src/components/widgets/StatTileWidget.vue')['default']
    TrendChartWidget: typeof import('./src/components/widgets/TrendChartWidget.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UDropdownMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UEmpty: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Empty.vue')['default']
    UForm: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    UNavigationMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTable: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTextarea: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Textarea.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.10.0_57cd19d9475972ea6c7bb5b5278a25b1/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
    WidgetGrid: typeof import('./src/components/WidgetGrid.vue')['default']
  }
}
