"""add dashboard layouts

Revision ID: b20106b79865
Revises: bce32b20fdb2
Create Date: 2026-09-17 18:44:16.888200

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20106b79865'
down_revision: Union[str, Sequence[str], None] = 'bce32b20fdb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_layouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widgets', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Singleton row (id=1) seeded here so app code never needs a
    # get-or-create branch — the row is guaranteed to exist post-migration.
    dashboard_layouts = sa.table(
        'dashboard_layouts',
        sa.column('id', sa.Integer),
        sa.column('widgets', sa.JSON),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    now = datetime.utcnow()
    op.bulk_insert(dashboard_layouts, [{
        'id': 1,
        'widgets': [
            {'id': 'netWorthRings', 'type': 'netWorthRings', 'x': 0, 'y': 0, 'w': 12, 'h': 4},
            {'id': 'composition', 'type': 'composition', 'x': 0, 'y': 4, 'w': 12, 'h': 3},
            {'id': 'assetsByClass', 'type': 'assetsByClass', 'x': 0, 'y': 7, 'w': 12, 'h': 3},
            {'id': 'liabilitiesVsAssets', 'type': 'liabilitiesVsAssets', 'x': 0, 'y': 10, 'w': 12, 'h': 2},
            {'id': 'recentValuations', 'type': 'recentValuations', 'x': 0, 'y': 12, 'w': 12, 'h': 3},
        ],
        'created_at': now,
        'updated_at': now,
    }])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard_layouts')
    # ### end Alembic commands ###
