"""add fully_priced to valuations

Revision ID: b5650195af0e
Revises: 49dec532a774
Create Date: 2026-09-22 11:30:19.026923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5650195af0e'
down_revision: Union[str, Sequence[str], None] = '49dec532a774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default so existing rows (all manual or pre-fix auto valuations, which have no way
    # to know their own pricing status retroactively) backfill to True — same as any Valuation
    # the model itself defaults to when nothing says otherwise.
    op.add_column(
        'valuations',
        sa.Column('fully_priced', sa.Boolean(), nullable=False, server_default=sa.true()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('valuations', 'fully_priced')
    # ### end Alembic commands ###
