"""add multi-currency support

Revision ID: bce32b20fdb2
Revises: 6e5dde3effa2
Create Date: 2026-09-16 15:00:58.864754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce32b20fdb2'
down_revision: Union[str, Sequence[str], None] = '6e5dde3effa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rate_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base', sa.String(length=3), nullable=False),
    sa.Column('quote', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base', 'quote', name='uq_fx_rate_cache_base_quote')
    )
    # server_default backfills existing rows (self-hosted deployments with data
    # already in the accounts/liabilities tables) as EUR, matching the app's
    # implicit assumption before this migration.
    op.add_column(
        'accounts',
        sa.Column(
            'currency',
            sa.Enum('EUR', 'USD', 'GBP', 'CHF', 'JPY', 'CAD', 'AUD', name='currency'),
            nullable=False,
            server_default='EUR',
        ),
    )
    op.add_column(
        'liabilities',
        sa.Column(
            'currency',
            sa.Enum('EUR', 'USD', 'GBP', 'CHF', 'JPY', 'CAD', 'AUD', name='currency'),
            nullable=False,
            server_default='EUR',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('liabilities', 'currency')
    op.drop_column('accounts', 'currency')
    op.drop_table('fx_rate_cache')
    # ### end Alembic commands ###
