"""add liability_balances table

Revision ID: ca53f19dfc20
Revises: b5650195af0e
Create Date: 2026-09-22 11:48:07.847832

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca53f19dfc20'
down_revision: Union[str, Sequence[str], None] = 'b5650195af0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liability_balances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liability_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['liability_id'], ['liabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Backfill: one balance entry per existing liability, from its current remaining_amount —
    # dated at its own start_date (reproducing get_net_worth_history's pre-existing flat
    # backward-projection exactly, as a safe no-op baseline) or at its created_at date if
    # start_date isn't set. Not a real historical reconstruction (see #82) — just enough that
    # every liability has at least one recorded point going forward, and no PATCH to its
    # remaining_amount is needed before the sync hook (app/services/liability_balance.py) starts
    # keeping this table current.
    liabilities = sa.table(
        'liabilities',
        sa.column('id', sa.Integer),
        sa.column('remaining_amount', sa.Numeric(14, 2)),
        sa.column('start_date', sa.Date),
        sa.column('created_at', sa.DateTime),
    )
    liability_balances = sa.table(
        'liability_balances',
        sa.column('liability_id', sa.Integer),
        sa.column('date', sa.Date),
        sa.column('remaining_amount', sa.Numeric(14, 2)),
        sa.column('note', sa.String),
        sa.column('created_at', sa.DateTime),
    )
    bind = op.get_bind()
    rows = bind.execute(
        sa.select(liabilities.c.id, liabilities.c.remaining_amount, liabilities.c.start_date, liabilities.c.created_at)
    ).fetchall()
    now = datetime.utcnow()
    backfill = [
        {
            'liability_id': row.id,
            'date': row.start_date or row.created_at.date(),
            'remaining_amount': row.remaining_amount,
            'note': 'Backfilled from remaining_amount at migration time (see #82)',
            'created_at': now,
        }
        for row in rows
    ]
    if backfill:
        op.bulk_insert(liability_balances, backfill)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liability_balances')
    # ### end Alembic commands ###
